### ISSUE TITLE
npm start runs into ERR!

### ISSUE THREAD

**Issue by M1r4kulix** [Autodesk-Forge/forge-boilers.nodejs#12]
I try to start npm and ran into an error, i'am an absolute rookie and have no idea what's the problem.
Maybe some one can bring some light into my darkness.

TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.<anonymous> (C:\Users\Lieme\Desktop\Python Learning\viewer-walkthrough-online.viewer-master\start.js:106:35)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! viewer-walkthrough-online.viewer@2.0.0 start: `node start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the viewer-walkthrough-online.viewer@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by PiotrBuda91** [comment]
Im getting the same error - was it fixed yet?
